eithers/urls.py
from django.urls import path
from . import views


app_name = 'eithers'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
]

practice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eithers/', include('eithers.urls')),
]

eithers/models.py
from django.db import models


class Game(models.Model):
    title = models.TextField()
    issue_a = models.TextField()
    issue_b = models.TextField()
    img_url = models.TextField()


class Comment(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    content = models.TextField()
    voted = models.CharField(max_length=30)

eithers/forms.py
from django import forms
from .models import Game, Comment


class GameForm(forms.ModelForm):

    class Meta:
        model = Game
        fields = '__all__'


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ('game',)

eithers/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods, require_POST, require_safe

from .models import Game, Comment
from .forms import GameForm, CommentForm


@require_safe
def index(request):
    games = Game.objects.all()
    length = Game.objects.count()
    random = Game.objects.order_by('?').first()
    context = {
        'games': games,
        'length': length,
        'random': random,
    }
    return render(request, 'eithers/index.html', context)


@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = GameForm(request.POST)
        if form.is_valid():
            game = form.save()
            return redirect('eithers:detail', game.pk)
    else:
        form = GameForm()
    context = {
        'form': form,
    }
    return render(request, 'eithers/create.html', context)


@require_safe
def detail(request, pk):
    game = Game.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = game.comment_set.all()

    if len(comments) != 0:
        left = round(len(comments.filter(voted='primary')) /
                     len(comments) * 100, 2)
        right = 100 - left
    else:
        left, right = 50, 50

    context = {
        'game': game,
        'comment_form': comment_form,
        'comments': comments,
        'left': left,
        'right': right,
    }
    return render(request, 'eithers/detail.html', context)


@require_POST
def comments_create(request, pk):
    game = Game.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.game = game
        comment.user = request.user
        comment.save()
    return redirect('eithers:detail', game.pk)

eithers/templates/eithers/create.html
{% extends 'base.html' %}

{% block content %}

  <body class="about-us bg-gray-200">
    <!-- Navbar -->
    <div class="container position-sticky z-index-sticky top-0">
      <div class="row">
        <div class="col-12">
          <nav class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
            <div class="container-fluid px-0">
              <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url 'eithers:index' %}" rel="tooltip" data-placement="bottom">
                Either Game
              </a>
              <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon mt-2">
                  <span class="navbar-toggler-bar bar1"></span>
                  <span class="navbar-toggler-bar bar2"></span>
                  <span class="navbar-toggler-bar bar3"></span>
                </span>
              </button>
              <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
                <ul class="navbar-nav navbar-nav-hover ms-auto">
                  <li class="nav-item ms-lg-auto">
                    <a class="nav-link nav-link-icon me-2" href="https://github.com/joyful0920">
                      <i class="fa fa-github me-1"></i>
                      <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Star us on Github">Github</p>
                    </a>
                  </li>
                  <li class="nav-item my-auto ms-3 ms-lg-0">
                    <a href="{% url 'eithers:index' %}" class="btn btn-sm  bg-gradient-primary  mb-0 me-1 mt-2 mt-md-0">GAME START</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          <!-- End Navbar -->
        </div>
      </div>
    </div>
    <!-- End Navbar -->
    <!-- Header -->
    <section>
      <div class="page-header min-vh-100">
        <div class="container">
          <div class="row">
            <div class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 start-0 text-center justify-content-center flex-column">
              <div class="position-relative h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center" style="background-image: url('https://images.unsplash.com/photo-1614995008867-32eef7bff38c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1074&q=80'); background-size: cover; background-position: center;" loading="lazy"></div>
            </div>
            <div class="col-xl-5 col-lg-6 col-md-7 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-5">
              <div class="card d-flex blur justify-content-center shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
                <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent">
                  <div class="bg-gradient-primary shadow-primary border-radius-lg p-3">
                    <h3 class="text-white text-primary mb-0">New Question</h3>
                  </div>
                </div>
                <div class="card-body">
                  <p class="pb-3">
                    Create a custom game.
                  </p>
                  <form id="create-form" action="{% url 'eithers:create' %}" method="POST" autocomplete="off">
                    {% csrf_token %}
                    <div class="card-body p-0 my-3">
                      <div class="form-group mb-0 mt-md-0 mt-4">
                        <div class="input-group input-group-lg input-group-static mb-4">
                          <label>Title</label>
                          <textarea name="title" class="form-control" id="title" rows="1"></textarea>
                        </div>
                      </div>
                      <div class="form-group mb-0 mt-md-0 mt-4">
                        <div class="input-group input-group-lg input-group-static mb-4">
                          <label>Image URL</label>
                          <textarea name="img_url" class="form-control" id="img_url" rows="1"></textarea>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-6">
                          <div class="input-group input-group-lg input-group-static mb-4">
                            <label>issue a</label>
                            <textarea name="issue_a" class="form-control" id="issue_a" rows="1"></textarea>
                          </div>
                        </div>
                        <div class="col-md-6 ps-md-2">
                          <div class="input-group input-group-lg input-group-static mb-4">
                            <label>issue b</label>
                            <textarea name="issue_b" class="form-control" id="issue_b" rows="1"></textarea>
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-12 text-center">
                          <button type="submit" class="btn bg-gradient-primary mt-3 mb-0">Submit</button>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End Header -->
  </body>
{% endblock content %}

eithers/templates/eithers/detail.html
{% extends 'base.html' %}

{% block content %}

  <body class="about-us">
    <!-- Navbar -->
    <div class="container position-sticky z-index-sticky top-0">
      <div class="row">
        <div class="col-12">
          <nav class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
            <div class="container-fluid px-0">
              <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url 'eithers:index' %}" rel="tooltip" data-placement="bottom">
                Either Game
              </a>
              <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon mt-2">
                  <span class="navbar-toggler-bar bar1"></span>
                  <span class="navbar-toggler-bar bar2"></span>
                  <span class="navbar-toggler-bar bar3"></span>
                </span>
              </button>
              <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
                <ul class="navbar-nav navbar-nav-hover ms-auto">
                  <li class="nav-item ms-lg-auto">
                    <a class="nav-link nav-link-icon me-2" href="https://github.com/joyful0920" target="_blank">
                      <i class="fa fa-github me-1"></i>
                      <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Star us on Github">Github</p>
                    </a>
                  </li>
                  <li class="nav-item my-auto ms-3 ms-lg-0">
                    <a href="{% url 'eithers:index' %}" class="btn btn-sm  bg-gradient-primary  mb-0 me-1 mt-2 mt-md-0">GAME START</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          <!-- End Navbar -->
        </div>
      </div>
    </div>
    <!-- End Navbar -->
    <!-- Header -->
    <header class="bg-gradient-dark">
      <div class="page-header min-vh-45" style="background-image: url('{{ game.img_url }}');">
        <span class="mask bg-gradient-dark opacity-6"></span>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-8 text-center mx-auto my-auto">
              <h1 class="text-white">DETAIL</h1>
              <p class="lead mb-4 text-white opacity-8">Vote for your favorite!</p>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- End Header -->
    <div class="container w-120 my-6">
      <div class="text-center">
        <h1 class="mb-3">{{ game.title }}</h1>
      </div>
      <div class="d-flex justify-content-between">
        <span class="text-primary font-weight-bolder fs-3">{{ game.issue_a }}</span>
        <span class="text-info font-weight-bolder fs-3">{{ game.issue_b }}</span>
      </div>
      <div class="progress mb-5">
        <div class="progress-bar progress-bar-striped progress-bar-animated bg-primary" role="progressbar" aria-label="Segment one" style="width: {{ left }}%; height: 30px;" aria-valuenow="{{ left }}" aria-valuemin="0" aria-valuemax="100">{{ left }}%</div>
        <div class="progress-bar progress-bar-striped progress-bar-animated bg-info" role="progressbar" aria-label="Segment two" style="width: {{ right }}%; height: 30px;" aria-valuenow="{{ right }}" aria-valuemin="0" aria-valuemax="100">{{ right }}%</div>
      </div>
      <div class="text-dark">
        <hr>
      </div>
      <h3 class="mb-3">댓글 작성</h3>
      <form action="{% url 'eithers:comments_create' game.pk %}" method="POST">
        {% csrf_token %}
        <label for="voted">Pick</label>
        <div class="input-group input-group-lg input-group-static mb-4">
          <div class="form-check mb-3">
            <input class="form-check-input" type="radio" name="voted" id="voted1" value="primary">
            <label class="custom-control-label" for="voted1">
              <span class="badge bg-gradient-primary">{{ game.issue_a }}</span></label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="radio" name="voted" id="voted2" value="info">
            <label class="custom-control-label" for="voted2">
              <span class="badge bg-gradient-info">{{ game.issue_b }}</span></label>
          </div>
        </div>
        <label>Content</label>
        <div class="input-group input-group-lg input-group-static mb-4">
          <textarea name="content" class="form-control" id="content" rows="1" required="required"></textarea>
        </div>
        <input type="submit" class="btn btn-lg bg-gradient-warning" value="작 성"></input>
      </form>
      <div class="text-dark">
        <hr>
      </div>
      <h3 class="mb-3">댓글 목록</h3>
      {% for comment in comments %}
        <button type="button" class="btn btn-lg btn-{{ comment.voted }}">{{ comment.content }}</button>
      {% endfor %}
    </div>
  </body>
{% endblock content %}

eithers/templates/eithers/index.html
{% extends 'base.html' %}

{% block content %}

  <body class="about-us bg-gray-200">
    <!-- Navbar -->
    <div class="container position-sticky z-index-sticky top-0">
      <div class="row">
        <div class="col-12">
          <nav class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
            <div class="container-fluid px-0">
              <a class="navbar-brand font-weight-bolder ms-sm-3" href="{% url 'eithers:index' %}" rel="tooltip" data-placement="bottom">
                Either Game
              </a>
              <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon mt-2">
                  <span class="navbar-toggler-bar bar1"></span>
                  <span class="navbar-toggler-bar bar2"></span>
                  <span class="navbar-toggler-bar bar3"></span>
                </span>
              </button>
              <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
                <ul class="navbar-nav navbar-nav-hover ms-auto">
                  <li class="nav-item ms-lg-auto">
                    <a class="nav-link nav-link-icon me-2" href="https://github.com/joyful0920" target="_blank">
                      <i class="fa fa-github me-1"></i>
                      <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Star us on Github">Github</p>
                    </a>
                  </li>
                  <li class="nav-item my-auto ms-3 ms-lg-0">
                    <a href="{% url 'eithers:index' %}" class="btn btn-sm  bg-gradient-primary  mb-0 me-1 mt-2 mt-md-0">GAME START</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          <!-- End Navbar -->
        </div>
      </div>
    </div>
    <!-- End Navbar -->
    <!-- Header -->
    <header class="bg-gradient-dark">
      <div class="page-header min-vh-45" style="background-image: url('https://images.unsplash.com/photo-1511512578047-dfb367046420?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1471&q=80');">
        <span class="mask bg-gradient-dark opacity-6"></span>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-8 text-center mx-auto my-auto">
              <h1 class="text-white">Either Game</h1>
              <p class="lead mb-4 text-white opacity-8">Enjoy Worldwide Super Versus Game!</p>
              <a href="{% url 'eithers:create' %}" class="btn btn-lg bg-info text-white">New Question</a>
              {% if length > 0 %}
                <a href="{% url 'eithers:detail' random.pk %}" class="btn btn-lg bg-primary text-white">Random Game</a>
              {% else %}
                <a href="{% url 'eithers:create' %}" class="btn btn-lg bg-primary text-white">Random Game</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- End Header -->
    <div class="container w-120 mt-5" id="games">
      <div class="row justify-content-center">
        {% for game in games %}
          <div class="col-3 m-3">
            <div class="card text-center">
              <div class="overflow-hidden position-relative border-radius-lg bg-cover p-3" style="background-image: url('{{ game.img_url }}'); background-position: center;">
                <span class="mask bg-gradient-dark opacity-6"></span>
                <div class="card-body position-relative z-index-1 d-flex flex-column mt-3">
                  <h4 class="text-white font-weight-bolder">{{ game.title }}</h4>
                </div>
                <a href="{% url 'eithers:detail' game.pk %}" class="btn bg-warning text-white">Play</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </body>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet">
  <link href="{% static 'css/material-kit.min.css' %}" rel="stylesheet">
  <title>Either</title>
</head>
  <link rel="short icon" href="#">
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/material-kit.min.js' %}"></script>
</html>